# Generated by Django 5.1.4 on 2025-01-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='titul',
            new_name='titulo',
        ),
    ]
